// <auto-generated />
using System;
using LuckyDraw.Models.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LuckyDraw.Migrations
{
    [DbContext(typeof(IndustryExhibitionRTCContext))]
    partial class IndustryExhibitionRTCContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LuckyDraw.Models.Customer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<bool?>("AGVnAMRSolutions")
                        .HasColumnType("bit");

                    b.Property<bool?>("AutomaticMachineManufacturingSolutions")
                        .HasColumnType("bit");

                    b.Property<bool?>("AutomationEquipmentinProduction")
                        .HasColumnType("bit");

                    b.Property<string>("Company")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailAdress")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<bool?>("FacebookChannel")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GameScore")
                        .HasColumnType("int");

                    b.Property<int?>("Gender")
                        .HasColumnType("int");

                    b.Property<bool?>("IoTSolutions")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsPlayedGame")
                        .HasColumnType("bit");

                    b.Property<int?>("LuckyNumber")
                        .HasColumnType("int");

                    b.Property<bool?>("MachineVisionSolutions")
                        .HasColumnType("bit")
                        .HasComment("Giải pháp xử lý ảnh công nghiệp Machine Vision/Machine Vision Industrial Image Processing Solutions");

                    b.Property<bool?>("MailChannel")
                        .HasColumnType("bit");

                    b.Property<bool?>("OtherChannel")
                        .HasColumnType("bit");

                    b.Property<bool?>("OtherSolutions")
                        .HasColumnType("bit");

                    b.Property<bool?>("PartnersChannel")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<bool?>("SmartWarehouseSolutions")
                        .HasColumnType("bit")
                        .HasComment("Giải pháp quản lý kho thông minh/Smart Warehouse Solutions");

                    b.Property<DateTime?>("TimeEndGame")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("TimeStartGame")
                        .HasColumnType("datetime");

                    b.Property<bool?>("WebsiteChannel")
                        .HasColumnType("bit");

                    b.Property<int?>("YearValue")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex(new[] { "PhoneNumber", "YearValue", "LuckyNumber" }, "unique_Phone_Year_Customer")
                        .IsUnique()
                        .HasFilter("[PhoneNumber] IS NOT NULL AND [YearValue] IS NOT NULL AND [LuckyNumber] IS NOT NULL");

                    b.ToTable("Customer", (string)null);
                });

            modelBuilder.Entity("LuckyDraw.Models.Prize", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("LuckyNumber")
                        .HasColumnType("int");

                    b.Property<string>("PrizeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("YearValue")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Prize", (string)null);
                });

            modelBuilder.Entity("LuckyDraw.Models.PrizeStudent", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("LuckyNumber")
                        .HasColumnType("int");

                    b.Property<string>("PrizeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("YearValue")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("PrizeStudent", (string)null);
                });

            modelBuilder.Entity("LuckyDraw.Models.Student", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<bool?>("Accounting")
                        .HasColumnType("bit")
                        .HasComment("Kế toán");

                    b.Property<bool?>("AutomotiveEngineeringTechnology")
                        .HasColumnType("bit")
                        .HasComment("Công nghệ kỹ thuật ô tô");

                    b.Property<bool?>("BusinessAdministration")
                        .HasColumnType("bit")
                        .HasComment("Quản trị kinh doanh");

                    b.Property<bool?>("ChemicalEngineeringTechnology")
                        .HasColumnType("bit")
                        .HasComment("Công nghệ kỹ thuật hóa học");

                    b.Property<bool?>("ComputerScience")
                        .HasColumnType("bit")
                        .HasComment("Khoa học máy tính");

                    b.Property<bool?>("ControlandAutomationEngineeringTechnology")
                        .HasColumnType("bit")
                        .HasComment("Công nghệ kỹ thuật điều khiển và tự động hóa");

                    b.Property<bool?>("ElectricalandElectronicsEngineeringTechnology")
                        .HasColumnType("bit")
                        .HasComment("Công nghệ kỹ thuật điện, điện tử");

                    b.Property<bool?>("ElectronicsandTelecommunicationsEngineeringTechnology")
                        .HasColumnType("bit")
                        .HasComment("Công nghệ kỹ thuật điện tử - viễn thông");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.Property<bool?>("EnglishLanguage")
                        .HasColumnType("bit")
                        .HasComment("Ngôn ngữ Anh");

                    b.Property<bool?>("FinanceandBanking")
                        .HasColumnType("bit")
                        .HasComment("Tài chính - Ngân hàng");

                    b.Property<string>("FullName")
                        .HasMaxLength(550)
                        .HasColumnType("nvarchar(550)");

                    b.Property<bool?>("InformationSystems")
                        .HasColumnType("bit")
                        .HasComment("Hệ thống thông tin");

                    b.Property<int?>("LuckyNumber")
                        .HasColumnType("int");

                    b.Property<int?>("Major")
                        .HasColumnType("int")
                        .HasComment("1.MechatronicsEngineeringTechnology; 2.MechanicalEngineeringTechnology	\r\n3. ElectronicsandTelecommunicationsEngineeringTechnology	\r\n4. ElectricalandElectronicsEngineeringTechnology	\r\n5. ControlandAutomationEngineeringTechnology	\r\n6. ChemicalEngineeringTechnology	\r\n7. ThermalEngineeringTechnology	\r\n8. AutomotiveEngineeringTechnology	\r\n9. InformationSystems\r\n10. Accounting	\r\n11. ComputerScience\r\n12. SoftwareEngineering	\r\n13. EnglishLanguage	\r\n14. BusinessAdministration	\r\n15. FinanceandBanking	\r\n16. OtherMajor");

                    b.Property<bool?>("MechanicalEngineeringTechnology")
                        .HasColumnType("bit")
                        .HasComment("Công nghệ kỹ thuật cơ khí");

                    b.Property<bool?>("MechatronicsEngineeringTechnology")
                        .HasColumnType("bit")
                        .HasComment("Công nghệ kỹ thuật cơ điện tử");

                    b.Property<bool?>("OtherMajor")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SchoolYear")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<bool?>("SoftwareEngineering")
                        .HasColumnType("bit")
                        .HasComment("Kỹ thuật phần mềm");

                    b.Property<bool?>("ThermalEngineeringTechnology")
                        .HasColumnType("bit")
                        .HasComment("Công nghệ kỹ thuật nhiệt");

                    b.Property<int?>("YearValue")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Student", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
